version: '3.8'

services:
  ghabz_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: telapp
    ports:
      - "6000:80"
    env_file:
      - Ghabz.env

  haproxy:
    image: docker.arvancloud.ir/haproxy:latest
    depends_on:
      - ghabz_app
    ports:
      - "80:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg